apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: nginx
    spec: 
      containers:
      - name: nginx
        image: sage007/simple-ngnix
        ports:
        - containerPort: 80

